typography_spectrum: 0.40499
color:
  brandColors:
    - '#ffffff'
    - '#252525'
    - '#0072c5'
    - '#f98605'
    - '#cb0003'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.22739
analytics:
  google: null
  facebook: null
  twitter: null
name: spinksa
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Testing
description: Test
purpose: []
